name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test-vuln-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: go test ./... -count=1

      - name: Vulnerability check
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: Cross build
        run: make cross-build
